#!/bin/bash

SSH_ACCOUNT="user@host"
REMOTE_DIR="/home/user/path"
SSH_PORT=22

upload_dir() {
    dirPathNoSlash=$(echo "$1" | sed 's:/*$::')
	echo "Uploading dir $1"
    rsync -avuzh --delete-after --port=$SSH_PORT "$dirPathNoSlash/" "$SSH_ACCOUNT:$REMOTE_DIR/$dirPathNoSlash/"
}

upload() {
	echo "Uploading $1"
	scp -P $SSH_PORT -r "$1" "$SSH_ACCOUNT:$REMOTE_DIR/$1"
}

download() {
	echo "Downloading $1"
	scp -P $SSH_PORT -r "$SSH_ACCOUNT:$REMOTE_DIR/$1" "$1"
}

if [[ $# == 0 ]]; then
	ssh $SSH_ACCOUNT
	exit 0
fi

while [[ $# > 0 ]]; do
	if [[ -z $ACTION ]]; then
		if [[ "$1" != "u" ]] && [[ "$1" != "d" ]]; then
			echo "When transferring first param must be 'u' or 'd'"
			exit 1
		fi
		ACTION="$1"
	else
		if [[ "$ACTION" == "u" ]]; then
            if [[ -d "$1" ]]; then
                upload_dir "$1"
            else
                upload_file "$1"
            fi
        fi
		if [[ "$ACTION" == "d" ]]; then download "$1"; fi
	fi
	shift
done

exit 0
