#!/bin/bash

URL="user@host"
REMOTE_DIR="/home/user/path"

upload() {
	echo "Uploading $1"
	scp -r "$1" "$URL:$REMOTE_DIR/$1"
}

download() {
	echo "Downloading $1"
	scp -r "$URL:$REMOTE_DIR/$1" "$1"
}

if [[ $# == 0 ]]; then
	ssh $URL
	exit 0
fi

while [[ $# > 0 ]]; do
	if [[ -z $ACTION ]]; then
		if [[ "$1" != "u" ]] && [[ "$1" != "d" ]]; then
			echo "When transferring first param must be 'u' or 'd'"
			exit 1
		fi
		ACTION="$1"
	else
		if [[ "$ACTION" == "u" ]]; then upload "$1"; fi
		if [[ "$ACTION" == "d" ]]; then download "$1"; fi
	fi
	shift
done

exit 0
